<?php

namespace Juniyasyos\FilamentLaravelBackup\Support;

class BackupSettingsDefaults
{
    public static function all(): array
    {
        return [
            [
                'key' => 'backup.general.timeout',
                'name' => 'Backup Timeout',
                'description' => 'Maximum time allowed for the backup process in seconds.',
                'group' => 'general',
                'type' => 'integer',
                'value' => 3600,
                'sort_order' => 1,
            ],
            [
                'key' => 'backup.general.queue',
                'name' => 'Queue Name',
                'description' => 'Queue used to run backup jobs.',
                'group' => 'general',
                'type' => 'string',
                'value' => 'default',
                'sort_order' => 2,
            ],
            [
                'key' => 'backup.general.cleanup_enabled',
                'name' => 'Auto Cleanup Enabled',
                'description' => 'Automatically remove old backups.',
                'group' => 'general',
                'type' => 'boolean',
                'value' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'backup.general.cleanup_days',
                'name' => 'Cleanup After Days',
                'description' => 'Delete backups older than this number of days.',
                'group' => 'general',
                'type' => 'integer',
                'value' => 30,
                'sort_order' => 4,
            ],
            [
                'key' => 'backup.general.notifications_enabled',
                'name' => 'Email Notifications',
                'description' => 'Send email notifications for backup events.',
                'group' => 'general',
                'type' => 'boolean',
                'value' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'backup.storage.default_disk',
                'name' => 'Default Storage Disk',
                'description' => 'Primary disk used to store backups.',
                'group' => 'storage',
                'type' => 'string',
                'value' => 'local',
                'sort_order' => 1,
            ],
            [
                'key' => 'backup.storage.local.path',
                'name' => 'Local Storage Path',
                'description' => 'Relative local path for backup files.',
                'group' => 'storage',
                'type' => 'string',
                'value' => 'storage/app/backup',
                'sort_order' => 2,
            ],
            [
                'key' => 'backup.storage.s3.bucket',
                'name' => 'S3 Bucket Name',
                'description' => 'Amazon S3 bucket used for backup files.',
                'group' => 'storage',
                'type' => 'string',
                'value' => '',
                'sort_order' => 3,
            ],
            [
                'key' => 'backup.storage.s3.region',
                'name' => 'S3 Region',
                'description' => 'Amazon S3 region.',
                'group' => 'storage',
                'type' => 'string',
                'value' => 'us-east-1',
                'sort_order' => 4,
            ],
            [
                'key' => 'backup.storage.s3.key',
                'name' => 'S3 Access Key',
                'description' => 'Amazon S3 Access Key ID.',
                'group' => 'storage',
                'type' => 'string',
                'value' => '',
                'sort_order' => 5,
            ],
            [
                'key' => 'backup.storage.s3.secret',
                'name' => 'S3 Secret Key',
                'description' => 'Amazon S3 Secret Access Key.',
                'group' => 'storage',
                'type' => 'string',
                'value' => '',
                'sort_order' => 6,
            ],
            [
                'key' => 'backup.notifications.on_success',
                'name' => 'Notify on Success',
                'description' => 'Send a notification when a backup completes successfully.',
                'group' => 'notifications',
                'type' => 'boolean',
                'value' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'backup.notifications.on_failure',
                'name' => 'Notify on Failure',
                'description' => 'Send a notification when a backup fails.',
                'group' => 'notifications',
                'type' => 'boolean',
                'value' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'backup.notifications.progress_updates',
                'name' => 'Progress Updates',
                'description' => 'Send periodic progress updates during backup.',
                'group' => 'notifications',
                'type' => 'boolean',
                'value' => false,
                'sort_order' => 3,
            ],
            [
                'key' => 'backup.notifications.recipients',
                'name' => 'Email Recipients',
                'description' => 'Email addresses that receive backup notifications.',
                'group' => 'notifications',
                'type' => 'json',
                'value' => [],
                'sort_order' => 4,
            ],
            [
                'key' => 'backup.notifications.notify_user',
                'name' => 'Notify Backup Creator',
                'description' => 'Send notifications to the user who initiated the backup.',
                'group' => 'notifications',
                'type' => 'boolean',
                'value' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'backup.security.require_permission',
                'name' => 'Require Permission',
                'description' => 'Require a specific permission to access backup features.',
                'group' => 'security',
                'type' => 'boolean',
                'value' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'backup.security.allowed_roles',
                'name' => 'Allowed Roles',
                'description' => 'Comma-separated list of roles allowed to access backup features.',
                'group' => 'security',
                'type' => 'string',
                'value' => '',
                'sort_order' => 2,
            ],
            [
                'key' => 'backup.security.encrypt_backups',
                'name' => 'Encrypt Backups',
                'description' => 'Encrypt backup files for additional security.',
                'group' => 'security',
                'type' => 'boolean',
                'value' => false,
                'sort_order' => 3,
            ],
            [
                'key' => 'backup.security.encryption_key',
                'name' => 'Encryption Key',
                'description' => 'Optional encryption key for backup files.',
                'group' => 'security',
                'type' => 'string',
                'value' => '',
                'sort_order' => 4,
            ],
        ];
    }
}
